FROM node:22-alpine
WORKDIR /usr/src/app

# install all deps (including dev)
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8192 9229

# use npx so we don’t need global nodemon
CMD ["npx", "nodemon", "--respawn", "--watch", ".", "--exec", "node index.js"]
