services:
  whatsapp-api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./templates.json:/usr/src/app/templates.json
      - ./baileys_store.json:/usr/src/app/baileys_store.json
      - ./lid_phone_mappings.json:/usr/src/app/lid_phone_mappings.json
      - ./alarms.json:/usr/src/app/alarms.json
      - ./technicianContacts.json:/usr/src/app/technicianContacts.json
    ports:
      - "8192:8192"
